services:
  - type: web
    name: xeno-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_ENV
        value: production
